name: snapdeeb
options:
  bundleIdPrefix: dev.inc
targets:
  snapdeeb:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - snapdeebApp.swift
      - ContentView.swift
      - HomeView.swift
      - AppsView.swift
      - SettingsView.swift
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.inc.snap
        MARKETING_VERSION: "5.1"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        ENABLE_PREVIEWS: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
